// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SBS_Repositories.Models;

public partial class OrderDetail
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Column("OrderID")]
    public Guid OrderId { get; set; }

    [Required]
    [StringLength(255)]
    public string ServiceName { get; set; }

    [Required]
    [StringLength(255)]
    public string ServiceDescription { get; set; }

    public double UnitPrice { get; set; }

    [JsonIgnore]
    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }
}