// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SBS_Repositories.Models;

[Table("Order")]
public partial class Order
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Column("CustomerID")]
    public int CustomerId { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    public double TotalPrice { get; set; }

    public string OrderNote { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("OrderCustomers")]
    public virtual UserAccount Customer { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("OrderEmployees")]
    public virtual UserAccount Employee { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}